gitlab/config/routes.rb
    match '/.well-known/webfinger' => 'jwks#webfinger', via: :options

    match '/oauth/token' => 'oauth/tokens#create', via: :options
    match '/oauth/revoke' => 'oauth/tokens#revoke', via: :options

    match '/-/jira_connect/oauth_application_id' => 'jira_connect/oauth_application_ids#show', via: :options
    match '/-/jira_connect/subscriptions(.:format)' => 'jira_connect/subscriptions#index', via: :options
    match '/-/jira_connect/subscriptions/:id' => 'jira_connect/subscriptions#delete', via: :options

    # Sign up
    scope path: '/users/sign_up', module: :registrations, as: :users_sign_up do
      Gitlab.ee do
        resource :welcome, only: [:show, :update], controller: 'welcome'
        resource :company, only: [:new, :create], controller: 'company'
        resources :groups, only: [:new, :create]
      end
    end

    # Search
    get 'search' => 'search#show', as: :search
    get 'search/autocomplete' => 'search#autocomplete', as: :search_autocomplete
    get 'search/settings' => 'search#settings'
    get 'search/count' => 'search#count', as: :search_count
    get 'search/opensearch' => 'search#opensearch', as: :search_opensearch

    Gitlab.ee do
      get 'search/aggregations' => 'search#aggregations', as: :search_aggregations
    end

    # JSON Web Token
    get 'jwt/auth' => 'jwt#auth'
    post 'jwt/auth', to: proc { [404, {}, ['']] }

    # Health check
    get 'health_check(/:checks)' => 'health_check#index', as: :health_check

    # Terraform service discovery
    get '.well-known/terraform.json' => 'terraform/services#index', as: :terraform_services

    # Begin of the /-/ scope.
    # Use this scope for all new global routes.
    scope path: '-' do
      # Autocomplete
      get '/autocomplete/users' => 'autocomplete#users'
      get '/autocomplete/users/:id' => 'autocomplete#user'
      get '/autocomplete/projects' => 'autocomplete#projects'
      get '/autocomplete/award_emojis' => 'autocomplete#award_emojis'
      get '/autocomplete/merge_request_target_branches' => 'autocomplete#merge_request_target_branches'
      get '/autocomplete/merge_request_source_branches' => 'autocomplete#merge_request_source_branches'
      get '/autocomplete/deploy_keys_with_owners' => 'autocomplete#deploy_keys_with_owners'

      Gitlab.ee do
        get '/autocomplete/project_groups' => 'autocomplete#project_groups'
        get '/autocomplete/project_routes' => 'autocomplete#project_routes'
        get '/autocomplete/namespace_routes' => 'autocomplete#namespace_routes'
        get '/autocomplete/group_subgroups' => 'autocomplete#group_subgroups'
      end

      # sandbox
      get '/sandbox/mermaid' => 'sandbox#mermaid'
      get '/sandbox/swagger' => 'sandbox#swagger'

      get '/:model/:model_id/uploads/:secret/:filename',
        to: 'banzai/uploads#show',
        constraints: {
          model: /project|group/,
          filename: %r{[^/]+}
        },
        as: 'banzai_upload'

      get '/whats_new' => 'whats_new#index'

      get 'offline' => "pwa#offline"
      get 'manifest' => "pwa#manifest", constraints: ->(req) { req.format == :json }

      scope module: 'clusters' do
        scope module: 'agents' do
          get '/kubernetes', to: 'dashboard#index', as: 'kubernetes_dashboard_index'
          get '/kubernetes/:agent_id(/*vueroute)', to: 'dashboard#show', as: 'kubernetes_dashboard'
        end
      end

      # HTTP Router
      # Creating a black hole for /-/http_router/version since it is taken by the
      # cloudflare worker, see: https://gitlab.com/gitlab-org/cells/http-router/-/issues/47
      match '/http_router/version', to: proc { [204, {}, ['']] }, via: :all

      # '/-/health' implemented by BasicHealthCheck middleware
      get 'liveness' => 'health#liveness'
      get 'readiness' => 'health#readiness'
      controller :metrics do
        get 'metrics', action: :index
        get 'metrics/system', action: :system
      end
      mount Peek::Railtie => '/peek', as: 'peek_routes'

      get 'runner_setup/platforms' => 'runner_setup#platforms'

      get 'acme-challenge/' => 'acme_challenges#show'

      scope :ide, as: :ide, format: false do
        get '/', to: 'ide#index'
        get '/project', to: 'ide#index'
        # note: This path has a hardcoded reference in the FE `app/assets/javascripts/ide/constants.js`
        get '/oauth_redirect', to: 'ide#oauth_redirect'

        scope path: 'project/:project_id', as: :project, constraints: { project_id: Gitlab::PathRegex.full_namespace_route_regex } do
          %w[edit tree blob].each do |action|
            get "/#{action}", to: 'ide#index'
            get "/#{action}/*branch/-/*path", to: 'ide#index'
            get "/#{action}/*branch/-", to: 'ide#index'
            get "/#{action}/*branch", to: 'ide#index'
          end

          get '/merge_requests/:merge_request_id', to: 'ide#index', constraints: { merge_request_id: /\d+/ }
          get '/', to: 'ide#index'
        end

        post '/reset_oauth_application_settings' => 'admin/applications#reset_web_ide_oauth_application_settings'
      end

      draw :operations
      draw :jira_connect
      draw :organizations

      Gitlab.ee do
        draw :remote_development
        draw :security
        draw :smartcard
        draw :trial_registration
        draw :country
        draw :country_state
        draw :gitlab_subscriptions
        draw :phone_verification
        draw :arkose

        scope '/push_from_secondary/:geo_node_id' do
          draw :git_http
        end
      end

      Gitlab.jh do
        draw :global_jh
      end

      if ENV['GITLAB_CHAOS_SECRET'] || Rails.env.development? || Rails.env.test?
        resource :chaos, only: [] do
          get :leakmem
          get :cpu_spin
          get :db_spin
          get :sleep
          get :kill
          get :quit
          post :gc
        end
      end

      resources :invites, only: [:show], constraints: { id: /[A-Za-z0-9_-]+/ } do
        member do
          post :accept
          match :decline, via: [:get, :post]
        end
      end

      resources :sent_notifications, only: [], constraints: { id: /\h{32}/ } do
        member do
          match :unsubscribe, via: [:get, :post]
        end
      end

      # Spam reports
      resources :abuse_reports, only: [:create] do
        collection do
          post :add_category
        end
      end

      # JWKS (JSON Web Key Set) endpoint
      # Used by third parties to verify CI_JOB_JWT
      get 'jwks' => 'jwks#index'

      draw :snippets
      draw :profile
      draw :user_settings

      post '/mailgun/webhooks' => 'mailgun/webhooks#process_webhook'

      # Deprecated route for permanent failures
      # https://gitlab.com/gitlab-org/gitlab/-/issues/362606
      post '/members/mailgun/permanent_failures' => 'mailgun/webhooks#process_webhook'

      get '/timelogs' => 'time_tracking/timelogs#index'

      post '/track_namespace_visits' => 'users/namespace_visits#create'

      get '/external_redirect' => 'external_redirect/external_redirect#index'
    end
    # End of the /-/ scope.

    concern :clusterable do
      resources :clusters, only: [:index, :show, :update, :destroy] do
        collection do
          get  :connect
          get  :new_cluster_docs
          post :create_user
        end

        resource :integration, controller: 'clusters/integrations', only: [] do
          collection do
            post :create_or_update
          end
        end

        member do
          Gitlab.ee do
            get :metrics, format: :json
            get :environments, format: :json
          end

          get :metrics_dashboard
          get :cluster_status, format: :json
          delete :clear_cache
        end
      end
    end

    resources :groups, only: [:index, :new, :create]

    get '/-/g/:id' => 'groups/redirect#redirect_from_id'

    draw :group

    resources :projects, only: [:index, :new, :create]

    get '/projects/:id' => 'projects/redirect#redirect_from_id'
    get '/-/p/:id' => 'projects/redirect#redirect_from_id'

    draw :git_http
    draw :api
    draw :activity_pub
    draw :customers_dot
    draw :device_auth
    draw :sidekiq
    draw :help
    draw :google_api
    draw :import
    draw :uploads
    draw :explore
    draw :admin
    draw :dashboard
    draw :identity_verification
    draw :user
    draw :project
    draw :unmatched_project
    draw :well_known

    # Issue https://gitlab.com/gitlab-org/gitlab/-/issues/210024
    scope as: 'deprecated' do
      # Issue https://gitlab.com/gitlab-org/gitlab/-/issues/223719
      get '/snippets/:id/raw',
        to: 'snippets#raw',
        format: false,
        constraints: { id: /\d+/ }

      Gitlab::Routing.redirect_legacy_paths(self, :snippets)
    end

    Gitlab.ee do
      get '/sitemap' => 'sitemap#show', format: :xml
    end

    # Creates shorthand helper methods for project resources.
    # For example; for the `namespace_project_path` this also creates `project_path`.
    #
    # TODO: We don't need the `Gitlab::Routing` module at all as we can use
    # the `direct` DSL method of Rails to define url helpers. Move all the
    # custom url helpers to use the `direct` DSL method and remove the `Gitlab::Routing`.
    # For more information: https://gitlab.com/groups/gitlab-org/-/epics/9866
    Gitlab::Application.routes.set.filter_map { |route| route.name if route.name&.include?('namespace_project') }.each do |name|
      new_name = name.sub('namespace_project', 'project')

      direct(new_name) do |project, *args|
        # This is due to a bug I've found in Rails.
        # For more information: https://gitlab.com/gitlab-org/gitlab/-/issues/299591
        args.pop if args.last == {}

        send("#{name}_url", project&.namespace, project, *args)
      end
    end

    root to: "root#index"

    get '*unmatched_route', to: 'application#route_not_found', format: false

    # Load all custom URLs definitions via `direct' after the last route

gitlab/app/models/work_items/widgets/notifications.rb
# frozen_string_literal: true

module WorkItems
  module Widgets
    class Notifications < Base
      delegate :subscribed?, to: :work_item
    end
  end
end

gitlab/app/controllers/profiles/accounts_controller.rb
# frozen_string_literal: true

class Profiles::AccountsController < Profiles::ApplicationController
  include AuthHelper

  feature_category :system_access
  urgency :low, [:show]

  def show
    push_frontend_feature_flag(:delay_delete_own_user)
    render(locals: show_view_variables)
  end

  def unlink
    provider = params[:provider]
    identity = find_identity(provider)

    return render_404 unless identity

    if unlink_provider_allowed?(provider)
      identity.destroy
    else
      flash[:alert] = _("You are not allowed to unlink your primary login account")
    end

    redirect_to profile_account_path
  end

  private

  def show_view_variables
    {}
  end

  def find_identity(provider)
    return current_user.atlassian_identity if provider == 'atlassian_oauth2'

    current_user.identities.find_by(provider: provider) # rubocop: disable CodeReuse/ActiveRecord
  end
end

Profiles::AccountsController.prepend_mod_with('Profiles::AccountsController')

gitlab/app/controllers/profiles/application_controller.rb
# frozen_string_literal: true

class Profiles::ApplicationController < ApplicationController
  layout 'profile'
end

gitlab/app/controllers/profiles/avatars_controller.rb
# frozen_string_literal: true

class Profiles::AvatarsController < Profiles::ApplicationController
  feature_category :user_profile

  def destroy
    @user = current_user

    Users::UpdateService.new(current_user, user: @user).execute(&:remove_avatar!)

    redirect_to user_settings_profile_path, status: :found
  end
end

gitlab/app/controllers/profiles/chat_names_controller.rb
# frozen_string_literal: true

class Profiles::ChatNamesController < Profiles::ApplicationController
  before_action :chat_name_token, only: [:new]
  before_action :chat_name_params, only: [:new, :create, :deny]

  feature_category :integrations

  def index
    @chat_names = current_user.chat_names
  end

  def new
    @integration_name = integration_name
  end

  def create
    new_chat_name = current_user.chat_names.new(chat_name_params)

    if new_chat_name.save
      flash[:notice] = _("Authorized %{new_chat_name}") % { new_chat_name: new_chat_name.chat_name }
    else
      flash[:alert] = _("Could not authorize chat nickname. Try again!")
    end

    delete_chat_name_token
    redirect_to profile_chat_names_path
  end

  def deny
    delete_chat_name_token

    flash[:notice] =
      _("Denied authorization of chat nickname %{user_name}.") % { user_name: chat_name_params[:user_name] }

    redirect_to profile_chat_names_path
  end

  def destroy
    @chat_name = chat_names.find(params[:id])

    if @chat_name.destroy
      flash[:notice] = _("Deleted chat nickname: %{chat_name}!") % { chat_name: @chat_name.chat_name }
    else
      flash[:alert] = _("Could not delete chat nickname %{chat_name}.") % { chat_name: @chat_name.chat_name }
    end

    redirect_to profile_chat_names_path, status: :found
  end

  private

  def delete_chat_name_token
    chat_name_token.delete
  end

  def chat_name_params
    @chat_name_params ||= chat_name_token.get || render_404
  end

  def chat_name_token
    return render_404 unless params[:token] || render_404

    @chat_name_token ||= Gitlab::ChatNameToken.new(params[:token])
  end

  def chat_names
    @chat_names ||= current_user.chat_names
  end

  def integration_name
    return s_('Integrations|GitLab for Slack app') if slack_app_params?

    s_('Integrations|Mattermost slash commands')
  end

  def slack_app_params?
    chat_name_params[:team_id].start_with?('T') &&
      chat_name_params[:chat_id].start_with?('U', 'W')
  end
end

gitlab/app/helpers/notifications_helper.rb
# frozen_string_literal: true

module NotificationsHelper
  include IconsHelper

  def notification_icon_class(level)
    case level.to_sym
    when :disabled, :owner_disabled
      'notifications-off'
    when :participating
      'notifications'
    when :watch
      'eye'
    when :mention
      'at'
    when :global
      'earth'
    end
  end

  def notification_icon_level(notification_setting, emails_disabled = false)
    if emails_disabled
      'owner_disabled'
    elsif notification_setting.global?
      current_user.global_notification_setting.level
    else
      notification_setting.level
    end
  end

  def notification_icon(level)
    icon = notification_icon_class(level)
    return '' unless icon

    sprite_icon(icon)
  end

  def show_unsubscribe_title?(noteable)
    can?(current_user, "read_#{noteable.to_ability_name}".to_sym, noteable)
  end

  def can_read_project?(project)
    can?(current_user, :read_project, project)
  end

  def notification_dropdown_items(notification_setting)
    NotificationSetting.levels.each_key.map do |level|
      next if level == "custom"
      next if level == "global" && notification_setting.source.nil?

      level
    end.compact
  end
end

gitlab/app/helpers/profiles_helper.rb
# frozen_string_literal: true

module ProfilesHelper
  def commit_email_select_options(user)
    private_email = user.private_commit_email
    verified_emails = user.verified_emails - [private_email]

    [
      [s_('Use primary email (%{email})') % { email: user.email }, ''],
      [
        safe_format(s_("Profiles|Use a private email - %{email}"), email: private_email),
        Gitlab::PrivateCommitEmail::TOKEN
      ],
      *verified_emails
    ]
  end

  def attribute_provider_label(attribute)
    user_synced_attributes_metadata = current_user.user_synced_attributes_metadata
    if user_synced_attributes_metadata&.synced?(attribute)
      if user_synced_attributes_metadata.provider
        Gitlab::Auth::OAuth::Provider.label_for(user_synced_attributes_metadata.provider)
      else
        'LDAP'
      end
    end
  end

  def user_profile?
    params[:controller] == 'users'
  end

  def ssh_key_usage_types
    {
      s_('SSHKey|Authentication & Signing') => 'auth_and_signing',
      s_('SSHKey|Authentication') => 'auth',
      s_('SSHKey|Signing') => 'signing'
    }
  end

  # Overridden in EE::ProfilesHelper#ssh_key_expiration_tooltip
  def ssh_key_expiration_tooltip(key)
    return key.errors.full_messages.join(', ') if key.errors.full_messages.any?
  end

  # Overridden in EE::ProfilesHelper#ssh_key_expires_field_description
  def ssh_key_expires_field_description
    s_('Profiles|Optional but recommended. If set, key becomes invalid on the specified date.')
  end

  # Overridden in EE::ProfilesHelper#ssh_key_expiration_policy_enabled?
  def ssh_key_expiration_policy_enabled?
    false
  end

  # Overridden in EE::ProfilesHelper#prevent_delete_account?
  def prevent_delete_account?
    false
  end

  def user_profile_data(user)
    {
      profile_path: user_settings_profile_path,
      profile_avatar_path: profile_avatar_path,
      avatar_url: avatar_icon_for_user(user, current_user: current_user),
      has_avatar: user.avatar?.to_s,
      gravatar_enabled: gravatar_enabled?.to_s,
      gravatar_link: { hostname: Gitlab.config.gravatar.host, url: "https://#{Gitlab.config.gravatar.host}" }.to_json,

      brand_profile_image_guidelines: if current_appearance&.profile_image_guidelines?
                                        brand_profile_image_guidelines
                                      else
                                        ''
                                      end,

      cropper_css_path: ActionController::Base.helpers.stylesheet_path('lazy_bundles/cropper.css'),
      user_path: user_path(current_user),
      timezones: timezone_data_with_unique_identifiers.to_json,
      user_timezone: user.timezone,
      **user_status_properties(user)
    }
  end
end

ProfilesHelper.prepend_mod

gitlab/app/views/profiles/notifications/_email_settings.html.haml
.js-notification-email-listbox-input.gl-mb-3{ data: { label: _('Global notification email'), name: 'user[notification_email]', emails: @user.public_verified_emails.to_json, empty_value_text: _('Use primary email (%{email})') % { email: @user.email }, value: @user.notification_email, disabled: local_assigns.fetch(:email_change_disabled, nil) } }
.gl-text-subtle
  = local_assigns.fetch(:help_text, nil)

gitlab/app/views/profiles/notifications/_group_settings.html.haml
- emails_disabled = group.emails_disabled?

%li
  .md:gl-flex.gl-justify-between.gl-items-center
    .gl-mb-2.md:gl-mb-0
      %span.gl-mr-2
        = notification_icon(notification_icon_level(setting, emails_disabled))

      %span
        = link_to group.name, group_path(group)

    .gl-flex.gl-gap-3.gl-flex-wrap
      - if setting
        .js-vue-notification-dropdown{ data: { disabled: emails_disabled.to_s, dropdown_items: notification_dropdown_items(setting).to_json, notification_level: setting.level, help_page_path: help_page_path('user/profile/notifications.md'), group_id: group.id, show_label: "true" } }
      = form_for setting, url: profile_group_notifications_path(group), method: :put, html: { class: 'update-notifications gl-flex' } do |f|
        .js-notification-email-listbox-input{ data: {  name: 'notification_setting[notification_email]', emails: @user.public_verified_emails.to_json, empty_value_text: _('Global notification email') , value: setting.notification_email, placement: 'bottom-end' } }

gitlab/app/views/profiles/notifications/_project_settings.html.haml
- emails_disabled = project.emails_disabled?

%li
  .md:gl-flex.gl-justify-between.gl-items-center
    .gl-mb-2.md:gl-mb-0
      %span.gl-mr-2
        = notification_icon(notification_icon_level(setting, emails_disabled))

      %span
        = link_to_project(project)

    .gl-flex.gl-gap-3.gl-flex-wrap
      - if setting
        .js-vue-notification-dropdown{ data: { disabled: emails_disabled.to_s, dropdown_items: notification_dropdown_items(setting).to_json, notification_level: setting.level, help_page_path: help_page_path('user/profile/notifications.md'), project_id: project.id, container_class: 'gl-mr-3', show_label: "true" } }

gitlab/app/views/profiles/notifications/show.html.haml
- page_title _('Notifications')
- @force_desktop_expanded_sidebar = true

- if @user.errors.any?
  = render Pajamas::AlertComponent.new(variant: :danger) do |c|
    - c.with_body do
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

= hidden_field_tag :notification_type, 'global'

= render ::Layouts::SettingsSectionComponent.new(page_title) do |c|
  - c.with_description do
    = _('You can specify notification level per group or per project.')

  - c.with_body do
    .gl-mt-0
      = gitlab_ui_form_for @user, url: profile_notifications_path, method: :put, html: { class: 'update-notifications gl-mt-3 gl-mb-6' } do |f|
        = render_if_exists 'profiles/notifications/email_settings'

      = label_tag :global_notification_level, _('Global notification level'), class: "label-bold gl-mb-0"
      .gl-text-subtle.gl-mb-3
        = _('By default, all projects and groups use the global notifications setting.')

      .form-group.global-notification-setting.gl-mb-3
        - if @global_notification_setting
          .js-vue-notification-dropdown{ data: { dropdown_items: notification_dropdown_items(@global_notification_setting).to_json, notification_level: @global_notification_setting.level, help_page_path: help_page_path('user/profile/notifications.md'), show_label: 'true' } }

      = gitlab_ui_form_for @user, url: profile_notifications_path, method: :put do |f|
        .form-group
          = f.gitlab_ui_checkbox_component :notified_of_own_activity, _('Receive notifications about your own activity')

      = render ::Layouts::CrudComponent.new(_('Groups'),
        icon: 'group',
        count: @user_groups.total_count) do |c|
        - c.with_body do
          - if @user_groups.total_count > 0
            %ul.content-list
              - @group_notifications.each do |setting|
                = render 'group_settings', setting: setting, group: setting.source
          - else
            .gl-text-subtle= _('You do not belong to any groups yet.')

        - if @user_groups.total_count > 0
          - c.with_pagination do
            = paginate @user_groups, theme: 'gitlab'

      = render ::Layouts::CrudComponent.new(_('Projects'),
        icon: 'project',
        count: @project_notifications.size,
        options: { class: 'gl-mt-5' }) do |c|
        - c.with_description do
          = _('To specify the notification level per project of a group you belong to, visit the project page and change the notification level there.')
        - c.with_body do
          - if @project_notifications.size > 0
            %ul.content-list
              - @project_notifications.each do |setting|
                = render 'project_settings', setting: setting, project: setting.source
          - else
            .gl-text-subtle= _("You do not belong to any projects yet.")