gitlab/config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'

InitializerConnections.raise_if_new_database_connection do
  Rails.application.routes.draw do
    concern :access_requestable do
      get :request_access, on: :collection
      post :request_access, on: :collection
      post :approve_access_request, on: :member
    end

    concern :awardable do
      post :toggle_award_emoji, on: :member
    end

    favicon_redirect = redirect do |_params, _request|
      ActionController::Base.helpers.asset_url(Gitlab::Favicon.main)
    end
    get 'favicon.png', to: favicon_redirect
    get 'favicon.ico', to: favicon_redirect

    draw :development

    use_doorkeeper do
      controllers applications: 'oauth/applications',
        authorized_applications: 'oauth/authorized_applications',
        authorizations: 'oauth/authorizations',
        token_info: 'oauth/token_info',
        tokens: 'oauth/tokens'
    end
    put '/oauth/applications/:id/renew(.:format)' => 'oauth/applications#renew', as: :renew_oauth_application

    draw :oauth

    use_doorkeeper_openid_connect do
      controllers discovery: 'jwks'
    end

    use_doorkeeper_device_authorization_grant do
      controller device_authorizations: 'oauth/device_authorizations'
    end

    # Add OPTIONS method for CORS preflight requests
    match '/oauth/userinfo' => 'doorkeeper/openid_connect/userinfo#show', via: :options
    match '/oauth/discovery/keys' => 'jwks#keys', via: :options
    match '/.well-known/openid-configuration' => 'jwks#provider', via: :options
    match '/.well-known/webfinger' => 'jwks#webfinger', via: :options

    match '/oauth/token' => 'oauth/tokens#create', via: :options
    match '/oauth/revoke' => 'oauth/tokens#revoke', via: :options

    match '/-/jira_connect/oauth_application_id' => 'jira_connect/oauth_application_ids#show', via: :options
    match '/-/jira_connect/subscriptions(.:format)' => 'jira_connect/subscriptions#index', via: :options
    match '/-/jira_connect/subscriptions/:id' => 'jira_connect/subscriptions#delete', via: :options

    # Sign up
    scope path: '/users/sign_up', module: :registrations, as: :users_sign_up do
      Gitlab.ee do
        resource :welcome, only: [:show, :update], controller: 'welcome'
        resource :company, only: [:new, :create], controller: 'company'
        resources :groups, only: [:new, :create]
      end
    end

    # Search
    get 'search' => 'search#show', as: :search
    get 'search/autocomplete' => 'search#autocomplete', as: :search_autocomplete
    get 'search/settings' => 'search#settings'
    get 'search/count' => 'search#count', as: :search_count
    get 'search/opensearch' => 'search#opensearch', as: :search_opensearch

    Gitlab.ee do
      get 'search/aggregations' => 'search#aggregations', as: :search_aggregations
    end

    # JSON Web Token
    get 'jwt/auth' => 'jwt#auth'
    post 'jwt/auth', to: proc { [404, {}, ['']] }

    # Health check
    get 'health_check(/:checks)' => 'health_check#index', as: :health_check

    # Terraform service discovery
    get '.well-known/terraform.json' => 'terraform/services#index', as: :terraform_services

    # Begin of the /-/ scope.
    # Use this scope for all new global routes.
    scope path: '-' do
      # Autocomplete
      get '/autocomplete/users' => 'autocomplete#users'
      get '/autocomplete/users/:id' => 'autocomplete#user'
      get '/autocomplete/projects' => 'autocomplete#projects'
      get '/autocomplete/award_emojis' => 'autocomplete#award_emojis'
      get '/autocomplete/merge_request_target_branches' => 'autocomplete#merge_request_target_branches'
      get '/autocomplete/merge_request_source_branches' => 'autocomplete#merge_request_source_branches'
      get '/autocomplete/deploy_keys_with_owners' => 'autocomplete#deploy_keys_with_owners'

      Gitlab.ee do
        get '/autocomplete/project_groups' => 'autocomplete#project_groups'
        get '/autocomplete/project_routes' => 'autocomplete#project_routes'
        get '/autocomplete/namespace_routes' => 'autocomplete#namespace_routes'
        get '/autocomplete/group_subgroups' => 'autocomplete#group_subgroups'
      end

      # sandbox
      get '/sandbox/mermaid' => 'sandbox#mermaid'
      get '/sandbox/swagger' => 'sandbox#swagger'

      get '/:model/:model_id/uploads/:secret/:filename',
        to: 'banzai/uploads#show',
        constraints: {
          model: /project|group/,
          filename: %r{[^/]+}
        },
        as: 'banzai_upload'

      get '/whats_new' => 'whats_new#index'

      get 'offline' => "pwa#offline"
      get 'manifest' => "pwa#manifest", constraints: ->(req) { req.format == :json }

      scope module: 'clusters' do
        scope module: 'agents' do
          get '/kubernetes', to: 'dashboard#index', as: 'kubernetes_dashboard_index'
          get '/kubernetes/:agent_id(/*vueroute)', to: 'dashboard#show', as: 'kubernetes_dashboard'
        end
      end

      # HTTP Router
      # Creating a black hole for /-/http_router/version since it is taken by the
      # cloudflare worker, see: https://gitlab.com/gitlab-org/cells/http-router/-/issues/47
      match '/http_router/version', to: proc { [204, {}, ['']] }, via: :all

      # '/-/health' implemented by BasicHealthCheck middleware
      get 'liveness' => 'health#liveness'
      get 'readiness' => 'health#readiness'
      controller :metrics do
        get 'metrics', action: :index
        get 'metrics/system', action: :system
      end
      mount Peek::Railtie => '/peek', as: 'peek_routes'

      get 'runner_setup/platforms' => 'runner_setup#platforms'

      get 'acme-challenge/' => 'acme_challenges#show'

      scope :ide, as: :ide, format: false do
        get '/', to: 'ide#index'
        get '/project', to: 'ide#index'
        # note: This path has a hardcoded reference in the FE `app/assets/javascripts/ide/constants.js`
        get '/oauth_redirect', to: 'ide#oauth_redirect'

        scope path: 'project/:project_id', as: :project, constraints: { project_id: Gitlab::PathRegex.full_namespace_route_regex } do
          %w[edit tree blob].each do |action|
            get "/#{action}", to: 'ide#index'
            get "/#{action}/*branch/-/*path", to: 'ide#index'
            get "/#{action}/*branch/-", to: 'ide#index'
            get "/#{action}/*branch", to: 'ide#index'
          end

          get '/merge_requests/:merge_request_id', to: 'ide#index', constraints: { merge_request_id: /\d+/ }
          get '/', to: 'ide#index'
        end

        post '/reset_oauth_application_settings' => 'admin/applications#reset_web_ide_oauth_application_settings'
      end

      draw :operations
      draw :jira_connect
      draw :organizations

      Gitlab.ee do
        draw :remote_development
        draw :security
        draw :smartcard
        draw :trial_registration
        draw :country
        draw :country_state
        draw :gitlab_subscriptions
        draw :phone_verification
        draw :arkose

        scope '/push_from_secondary/:geo_node_id' do
          draw :git_http
        end
      end

      Gitlab.jh do
        draw :global_jh
      end

      if ENV['GITLAB_CHAOS_SECRET'] || Rails.env.development? || Rails.env.test?
        resource :chaos, only: [] do
          get :leakmem
          get :cpu_spin
          get :db_spin
          get :sleep
          get :kill
          get :quit
          post :gc
        end
      end

      resources :invites, only: [:show], constraints: { id: /[A-Za-z0-9_-]+/ } do
        member do
          post :accept
          match :decline, via: [:get, :post]
        end
      end

      resources :sent_notifications, only: [], constraints: { id: /\h{32}/ } do
        member do
          match :unsubscribe, via: [:get, :post]
        end
      end

      # Spam reports
      resources :abuse_reports, only: [:create] do
        collection do
          post :add_category
        end
      end

      # JWKS (JSON Web Key Set) endpoint
      # Used by third parties to verify CI_JOB_JWT
      get 'jwks' => 'jwks#index'

      draw :snippets
      draw :profile
      draw :user_settings

      post '/mailgun/webhooks' => 'mailgun/webhooks#process_webhook'

      # Deprecated route for permanent failures
      # https://gitlab.com/gitlab-org/gitlab/-/issues/362606
      post '/members/mailgun/permanent_failures' => 'mailgun/webhooks#process_webhook'

      get '/timelogs' => 'time_tracking/timelogs#index'

      post '/track_namespace_visits' => 'users/namespace_visits#create'

      get '/external_redirect' => 'external_redirect/external_redirect#index'
    end
    # End of the /-/ scope.

    concern :clusterable do
      resources :clusters, only: [:index, :show, :update, :destroy] do
        collection do
          get  :connect
          get  :new_cluster_docs
          post :create_user
        end

        resource :integration, controller: 'clusters/integrations', only: [] do
          collection do
            post :create_or_update
          end
        end

        member do
          Gitlab.ee do
            get :metrics, format: :json
            get :environments, format: :json
          end

          get :metrics_dashboard
          get :cluster_status, format: :json
          delete :clear_cache
        end
      end
    end

    resources :groups, only: [:index, :new, :create]

    get '/-/g/:id' => 'groups/redirect#redirect_from_id'

    draw :group

    resources :projects, only: [:index, :new, :create]

    get '/projects/:id' => 'projects/redirect#redirect_from_id'
    get '/-/p/:id' => 'projects/redirect#redirect_from_id'

    draw :git_http
    draw :api
    draw :activity_pub
    draw :customers_dot
    draw :device_auth
    draw :sidekiq
    draw :help
    draw :google_api
    draw :import
    draw :uploads
    draw :explore
    draw :admin
    draw :dashboard
    draw :identity_verification
    draw :user
    draw :project
    draw :unmatched_project
    draw :well_known

gitlab/app/controllers/projects/merge_requests/application_controller.rb
# frozen_string_literal: true

class Projects::MergeRequests::ApplicationController < Projects::ApplicationController
  before_action :check_merge_requests_available!
  before_action :merge_request
  before_action :authorize_read_merge_request!

  feature_category :code_review_workflow

  before_action do
    push_force_frontend_feature_flag(:glql_integration, project&.glql_integration_feature_flag_enabled?)
    push_force_frontend_feature_flag(:continue_indented_text, project&.continue_indented_text_feature_flag_enabled?)
  end

  private

  # Normally the methods with `check_(\w+)_available!` pattern are
  # handled by the `method_missing` defined in `ProjectsController::ApplicationController`
  # but that logic does not take the member roles into account, therefore, we handle this
  # case here manually.
  def check_merge_requests_available!
    render_404 if project_policy.merge_requests_disabled?
  end

  def project_policy
    ProjectPolicy.new(current_user, project)
  end

  def merge_request
    @issuable =
      @merge_request ||=
        merge_request_includes(@project.merge_requests).find_by_iid!(params[:id])

    return render_404 unless can?(current_user, :read_merge_request, @issuable)

    @issuable
  end

  def merge_request_includes(association)
    association.includes(preloadable_mr_relations) # rubocop:disable CodeReuse/ActiveRecord
  end

  def preloadable_mr_relations
    [:metrics, { assignees: :status }, { author: :status }]
  end

  def merge_request_params
    params.require(:merge_request).permit(merge_request_params_attributes)
  end

  def merge_request_params_attributes
    [
      :allow_collaboration,
      :description,
      :force_remove_source_branch,
      :lock_version,
      :milestone_id,
      :source_branch,
      :source_project_id,
      :state_event,
      :wip_event,
      :squash,
      :target_branch,
      :target_project_id,
      :task_num,
      :title,
      :discussion_locked,
      :issue_iid,
      :merge_after,
      { label_ids: [],
        assignee_ids: [],
        reviewer_ids: [],
        update_task: [:index, :checked, :line_number, :line_source] }
    ]
  end

  def set_pipeline_variables
    @pipelines = Ci::PipelinesForMergeRequestFinder
      .new(@merge_request, current_user)
      .execute
  end

  def close_merge_request_if_no_source_project
    return if @merge_request.source_project
    return unless @merge_request.open?

    @merge_request.close
  end

  # rubocop: disable CodeReuse/ActiveRecord
  def commit
    commit_id = params[:commit_id].presence
    return unless commit_id

    return unless @merge_request.all_commits.exists?(sha: commit_id) ||
      @merge_request.recent_context_commits.map(&:id).include?(commit_id)

    @commit ||= @project.commit(commit_id)
  end
  # rubocop: enable CodeReuse/ActiveRecord

  def build_merge_request
    params[:merge_request] ||= ActionController::Parameters.new(source_project: @project)
    new_params = merge_request_params.merge(diff_options: diff_options)

    # Gitaly N+1 issue: https://gitlab.com/gitlab-org/gitlab-foss/issues/58096
    Gitlab::GitalyClient.allow_n_plus_1_calls do
      @merge_request = ::MergeRequests::BuildService
        .new(project: project, current_user: current_user, params: new_params)
        .execute
    end
  end
end

Projects::MergeRequests::ApplicationController.prepend_mod_with('Projects::MergeRequests::ApplicationController')

gitlab/app/controllers/projects/merge_requests/conflicts_controller.rb
# frozen_string_literal: true

class Projects::MergeRequests::ConflictsController < Projects::MergeRequests::ApplicationController
  include IssuableActions

  before_action :authorize_can_resolve_conflicts!

  urgency :low, [
    :show,
    :conflict_for_path,
    :resolve_conflicts
  ]

  def show
    respond_to do |format|
      format.html do
        @issuable_sidebar = serializer.represent(@merge_request, serializer: 'sidebar')
        Gitlab::UsageDataCounters::MergeRequestActivityUniqueCounter
          .track_loading_conflict_ui_action(user: current_user)
      end

      format.json do
        if @conflicts_list.can_be_resolved_in_ui?
          render json: @conflicts_list
        elsif @merge_request.can_be_merged?
          render json: {
            message: _('The merge conflicts for this merge request have already been resolved. ' \
              'Please return to the merge request.'),
            type: 'error'
          }
        else
          render json: {
            message: _('The merge conflicts for this merge request cannot be resolved through GitLab. ' \
              'Please try to resolve them locally.'),
            type: 'error'
          }
        end
      end
    end
  end

  def conflict_for_path
    return render_404 unless @conflicts_list.can_be_resolved_in_ui?

    file = @conflicts_list.file_for_path(params[:old_path], params[:new_path])

    return render_404 unless file

    render json: file, full_content: true
  end

  def resolve_conflicts
    return render_404 unless @conflicts_list.can_be_resolved_in_ui?

    Gitlab::UsageDataCounters::MergeRequestActivityUniqueCounter.track_resolve_conflict_action(user: current_user)

    if @merge_request.can_be_merged?
      render status: :bad_request,
        json: { message: _('The merge conflicts for this merge request have already been resolved.') }
      return
    end

    begin
      ::MergeRequests::Conflicts::ResolveService
        .new(merge_request)
        .execute(current_user, params)

      flash[:notice] = _('All merge conflicts were resolved. The merge request can now be merged.')

      render json: { redirect_to: project_merge_request_path(@project, @merge_request, resolved_conflicts: true) }
    rescue Gitlab::Git::Conflict::Resolver::ResolutionError => e
      render status: :bad_request, json: { message: e.message }
    end
  end

  private

  alias_method :issuable, :merge_request

  def authorize_can_resolve_conflicts!
    @conflicts_list = ::MergeRequests::Conflicts::ListService.new(@merge_request)

    render_404 unless @conflicts_list.can_be_resolved_by?(current_user)
  end

  def serializer
    MergeRequestSerializer.new(current_user: current_user, project: project)
  end
end

gitlab/app/controllers/projects/merge_requests/content_controller.rb
# frozen_string_literal: true

class Projects::MergeRequests::ContentController < Projects::MergeRequests::ApplicationController
  # @merge_request.check_mergeability is not executed here since
  # widget serializer calls it via mergeable? method
  # but we might want to call @merge_request.check_mergeability
  # for other types of serialization

  before_action :close_merge_request_if_no_source_project
  before_action :set_polling_header
  around_action :allow_gitaly_ref_name_caching

  FAST_POLLING_INTERVAL = 10.seconds.in_milliseconds
  SLOW_POLLING_INTERVAL = 5.minutes.in_milliseconds

  urgency :low, [
    :widget,
    :cached_widget
  ]

  def widget
    respond_to do |format|
      format.json do
        render json: serializer(MergeRequestPollWidgetEntity)
      end
    end
  end

  def cached_widget
    respond_to do |format|
      format.json do
        render json: serializer(MergeRequestPollCachedWidgetEntity)
      end
    end
  end

  private

  def set_polling_header
    interval = merge_request.open? ? FAST_POLLING_INTERVAL : SLOW_POLLING_INTERVAL
    Gitlab::PollingInterval.set_header(response, interval: interval)
  end

  def serializer(entity)
    serializer = MergeRequestSerializer.new(current_user: current_user, project: merge_request.project)
    serializer.represent(merge_request, {}, entity)
  end
end

gitlab/app/views/projects/merge_requests/creations/_diffs.html.haml
- if @merge_request.can_be_created
  = render "projects/diffs/diffs", diffs: @diffs, environment: @environment, show_whitespace_toggle: false
- else
  .nothing-here-block
    This merge request cannot be created.

gitlab/app/views/projects/merge_requests/creations/_new_compare.html.haml
= render ::Layouts::PageHeadingComponent.new(_('New merge request'))

- if @saml_groups.present?
  = render Pajamas::AlertComponent.new(variant: :warning, dismissible: false) do |c|
    - c.with_body do
      = s_('GroupSAML|Some branches are inaccessible because your SAML session has expired. To access the branches, select the group’s path to reauthenticate.')
    - c.with_actions do
      .gl-flex.gl-flex-wrap
        - @saml_groups.each do |group|
          = render Pajamas::ButtonComponent.new(href: sso_group_saml_providers_path(group, { token: group.saml_discovery_token, redirect: project_new_merge_request_branch_from_path(@source_project) }), button_options: { class: "gl-mr-3 gl-mb-3" }) do
            = group.path

= gitlab_ui_form_for [@project, @merge_request], url: project_new_merge_request_path(@project), method: :get, html: { class: "merge-request-form" } do |f|
  - if params[:nav_source].present?
    = hidden_field_tag(:nav_source, params[:nav_source])
  .js-merge-request-new-compare.row{ data: mr_compare_form_data(current_user, @merge_request) }
    .col-lg-6
      .card-new-merge-request
        %h2.gl-text-size-h2
          = _('Source branch')
        #js-source-project-dropdown{ data: { current_project: { value: f.object.source_project_id.to_s, text: f.object.source_project.full_path, refsUrl: refs_project_path(f.object.source_project) }.to_json, current_branch: { value: f.object.source_branch.presence, text: f.object.source_branch.presence }.to_json } }

    .col-lg-6
      .card-new-merge-request
        %h2.gl-text-size-h2
          = _('Target branch')
        #js-target-project-dropdown{ data: { target_projects_path: project_new_merge_request_json_target_projects_path(@project), current_project: { value: f.object.target_project_id.to_s, text: f.object.target_project.full_path, refsUrl: refs_project_path(f.object.target_project) }.to_json, current_branch: { value: f.object.target_branch.presence, text: f.object.target_branch.presence }.to_json } }

  - if @merge_request.errors.any?
    = form_errors(@merge_request)
  .row
    .col-12
      = f.submit _('Compare branches and continue'), data: { testid: 'compare-branches-button' }, pajamas_button: true

gitlab/app/views/projects/merge_requests/creations/_new_submit.html.haml
= render ::Layouts::PageHeadingComponent.new(_('New merge request'))
= gitlab_ui_form_for [@project, @merge_request], html: { class: 'merge-request-form common-note-form js-quick-submit' } do |f|
  = render 'shared/issuable/form', f: f, issuable: @merge_request, commits: @commits, presenter: @mr_presenter
  = f.hidden_field :source_project_id
  = f.hidden_field :source_branch
  = f.hidden_field :target_project_id
  = f.hidden_field :target_branch, id: ''

  - if params[:nav_source].present?
    = hidden_field_tag(:nav_source, params[:nav_source])

.mr-compare.merge-request.js-merge-request-new-submit.gl-mt-5{ 'data-mr-submit-action': "#{j params[:tab].presence || 'new'}" }
  - if @commits.empty?
    .merge-request-tabs-holder{ class: ("js-tabs-affix" unless ENV['RAILS_ENV'] == 'test') }
      .merge-request-tabs-container.gl-flex.gl-justify-between
        .scrolling-tabs-container.inner-page-scroll-tabs.is-smaller
          %button.fade-left{ type: 'button', title: _('Scroll left'), 'aria-label': _('Scroll left') }
            = sprite_icon('chevron-lg-left', size: 12)
          %button.fade-right{ type: 'button', title: _('Scroll right'), 'aria-label': _('Scroll right') }
            = sprite_icon('chevron-lg-right', size: 12)
          %ul.merge-request-tabs.nav.nav-tabs.nav-links.no-top.no-bottom.gl-flex.gl-flex-nowrap.gl-m-0.gl-p-0.js-tabs-affix
            %li.commits-tab.new-tab
              = link_to url_for(safe_params), data: {target: 'div#commits', action: 'new', toggle: 'tabvue'} do
                = _("Commits")
                = gl_badge_tag @total_commit_count, { class: 'gl-tab-counter-badge' }

    #diff-notes-app.tab-content
      #new.commits.tab-pane.active
        .gl-text-left.gl-my-5.gl-text-subtle
          %p
            = _("There are no commits yet.")
  - else
    .merge-request-tabs-holder{ class: ("js-tabs-affix" unless ENV['RAILS_ENV'] == 'test') }
      .merge-request-tabs-container.gl-flex.gl-justify-between
        .scrolling-tabs-container.inner-page-scroll-tabs.is-smaller
          %button.fade-left{ type: 'button', title: _('Scroll left'), 'aria-label': _('Scroll left') }
            = sprite_icon('chevron-lg-left', size: 12)
          %button.fade-right{ type: 'button', title: _('Scroll right'), 'aria-label': _('Scroll right') }
            = sprite_icon('chevron-lg-right', size: 12)
          %ul.merge-request-tabs.nav.nav-tabs.nav-links.no-top.no-bottom.gl-flex.gl-flex-nowrap.gl-m-0.gl-p-0.js-tabs-affix
            %li.commits-tab.new-tab
              = link_to url_for(safe_params), data: {target: 'div#commits', action: 'new', toggle: 'tabvue'} do
                = _("Commits")
                = gl_badge_tag @total_commit_count, { class: 'gl-tab-counter-badge' }
            - if @pipelines.any?
              %li.builds-tab
                = link_to url_for(safe_params.merge(action: 'pipelines')), data: {target: 'div#pipelines', action: 'pipelines', toggle: 'tabvue'} do
                  = _("Pipelines")
                  = gl_badge_tag @pipelines.size, { class: 'gl-tab-counter-badge' }
            %li.diffs-tab
              = link_to url_for(safe_params.merge(action: 'diffs')), data: {target: 'div#diffs', action: 'diffs', toggle: 'tabvue', testid: 'diffs-tab'} do
                = _("Changes")
                = gl_badge_tag @merge_request.diff_size, { class: 'gl-tab-counter-badge' }

    #diff-notes-app.tab-content
      #new.commits.tab-pane.active
        = render "projects/merge_requests/commits"
      #diffs.diffs.tab-pane{ class: "!gl-m-0" }
        -# This tab is always loaded via AJAX
      - if @pipelines.any?
        #pipelines.pipelines.tab-pane
          = render 'projects/merge_requests/pipelines', endpoint: url_for(safe_params.merge(action: 'pipelines', format: :json)), disable_initialization: true

  .mr-loading-status
    .loading.hide
      = gl_loading_icon(size: 'md')

gitlab/app/views/projects/merge_requests/creations/branch_from.html.haml
- if @commit
  = commit_to_html(@commit, @ref, @source_project)

gitlab/app/views/projects/merge_requests/creations/branch_to.html.haml
- if @commit
  = commit_to_html(@commit, @ref, @target_project)

gitlab/app/views/projects/merge_requests/creations/new.html.haml
- add_to_breadcrumbs _("Merge requests"), project_merge_requests_path(@project)
- breadcrumb_title _("New")
- page_title _("New merge request")
- add_page_specific_style 'page_bundles/pipelines'
- add_page_specific_style 'page_bundles/ci_status'
- add_page_specific_style 'page_bundles/merge_request'

- conflicting_mr = @merge_request.existing_mrs_targeting_same_branch.first

- if @merge_request.can_be_created && !params[:change_branches] && !conflicting_mr
  = render 'new_submit'
- else
  - if conflicting_mr
    - link_to_mr = link_to(conflicting_mr.to_reference, project_merge_request_path(conflicting_mr.target_project, conflicting_mr))
    - flash.now[:alert] = safe_format(s_("These branches already have an open merge request: %{link_to_mr}. Select a different source or target branch."), link_to_mr: link_to_mr)

  = render 'new_compare'